######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 20 20:59:21 2013
######################################################################
QT += webkit
TARGET = browser
TEMPLATE = app
SOURCES += main.cpp \
    browser.cpp
HEADERS += browser.h
FORMS += browser.ui \
    login.ui
